# **Arrays**

In [ ]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(a)
print(type(a))            # Prints "<class 'numpy.ndarray'>"

print(a.shape)            # Prints "(3,)"

print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print('\nRank 2 array: \n',b)
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]

Rank 2 array: 
 [[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4


**Different ways of creating Arrays**

In [ ]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"
print()
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

print()
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

print()
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

print()
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]

[[1. 1.]]

[[7 7]
 [7 7]]

[[1. 0.]
 [0. 1.]]

[[0.3729033  0.08565397]
 [0.77308152 0.14510649]]


**Slicing**

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print()

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"

print()
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(b)

print()
print(a[0, 1])   # Prints "77"
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[2 3]
 [6 7]]
2

[[77  3]
 [ 6  7]]

77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Accessing Rows and Columns from an array**

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print()

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**integer array indexing**

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


**Datatypes**

In [ ]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)

int64
float64
int64


# **Operations on Arrays**

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print('x:\n',x)
print('\n y:\n',y)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print('\n Elementwise sum:\n')
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print('\n Elementwise difference:\n')
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print('\n Elementwise product: \n')
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print('\n Elementwise division: \n')
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print('\n Elementwise square root: \n')
print(np.sqrt(x))

x:
 [[1. 2.]
 [3. 4.]]

 y:
 [[5. 6.]
 [7. 8.]]

 Elementwise sum:

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]

 Elementwise difference:

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]

 Elementwise product: 

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]

 Elementwise division: 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

 Elementwise square root: 

[[1.         1.41421356]
 [1.73205081 2.        ]]


Dot Product

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Sum

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


Transpose

In [ ]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


**Broadcasting**

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


# **Multi dimensional Array**

Operations:
*   Flattening
*   Reshaping



In [ ]:
arr=np.array([ [1,2,3,4,5,6], [2,3,455,66,3,8]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[  1   2   3   4   5   6]
 [  2   3 455  66   3   8]]
2
(2, 6)
12


Converting 2D array --> 1D array

In [ ]:
arr2=arr.flatten()
print(arr2)
print(arr2.shape)

[  1   2   3   4   5   6   2   3 455  66   3   8]
(12,)


Converting 1D array--> 2D array

In [ ]:
arr3=arr2.reshape(6,2)
print(arr3)
print(arr3.shape)

[[  1   2]
 [  3   4]
 [  5   6]
 [  2   3]
 [455  66]
 [  3   8]]
(6, 2)


1D --> 3D

In [ ]:
arr4=arr2.reshape(3,2,2)
print(arr4)

[[[  1   2]
  [  3   4]]

 [[  5   6]
  [  2   3]]

 [[455  66]
  [  3   8]]]


# **Multi dimensional Array --> Matrix**

In [ ]:
arr=np.array([ [1,2,3,4], [2,3,455,66]])
mat=np.matrix(arr)
print(mat)

[[  1   2   3   4]
 [  2   3 455  66]]


In [ ]:
mat=np.matrix('1,2,3 ; 2,3,4 ; 6,7,8')
print(mat)

print('\n Diagonal:',np.diagonal(mat))

print('\n Maximum:',mat.max())

[[1 2 3]
 [2 3 4]
 [6 7 8]]

 Diagonal: [1 3 8]

 Maximum: 8


In [ ]:
m1=np.matrix('1,2,3 ; 2,3,4 ; 6,7,8')
m2=np.matrix('1,1,2 ; 2,1,2 ; 3,1,1')

m3=m1+m2
print('Matrix Addition: \n ',m3)

m3=m1*m2
print('\n Matrix Multiplaication: \n',m3)
m3=np.matmul(m1,m2)
print(m3)

Matrix Addition: 
  [[2 3 5]
 [4 4 6]
 [9 8 9]]

 Matrix Multiplaication: 
 [[14  6  9]
 [20  9 14]
 [44 21 34]]
[[14  6  9]
 [20  9 14]
 [44 21 34]]


##**Writing outputs in Notpad file**

In [ ]:
text_file = open('output.txt', 'w')
text_file.write(str(x3))
text_file.close()

Matrix Assembly
https://numpy.org/doc/stable/reference/generated/numpy.block.html

In [ ]:
import numpy as np
M = np.zeros((5,5))
M1 = np.matrix([[1,2],[3,4]])
M2 = np.matrix([[1,2],[3,4]])
M[:2,:2] += M1
M[1:3, 1:3] += M2
M

##**Eigen Values Decomposition**

Numpy provides a function returning eigenvectors and eigenvalues
- the first array corresponds to the eigenvalues
- the second to the eigenvectors concatenated in columns:



In [ ]:
A = np.array([[5, 1], [3, 3]])
A

array([[5, 1],
       [3, 3]])

In [ ]:
np.linalg.eig(A)

(array([6., 2.]), array([[ 0.70710678, -0.31622777],
        [ 0.70710678,  0.9486833 ]]))