lambda,sorted

In [ ]:
ll=[['z',56,'hi'],['b',2,'te'],['c',666,'yu']]
print(ll[-1])

kkey=lambda x: x[-1]

print(kkey(ll))

sorted(ll)

sorted(ll, key= lambda y: y[-1])

['c', 666, 'yu']
['c', 666, 'yu']


[['z', 56, 'hi'], ['b', 2, 'te'], ['c', 666, 'yu']]

# **writing in text, json file**

In [ ]:
with open('test.txt', 'w') as fp:
    fp.write("Hello World")

In [ ]:
def square(n):
    return n**2

In [ ]:
with open('test_1.txt', 'w') as fp:
    fp.write(str(square(5)) + "\n" + str(square(3)))  #always takes in string

In [ ]:
a = [1,2,3,4,5]
b = ""

for each_element in a:
    b = b + "\n" + str(square(each_element))
b = b.strip()
print(b)

1
4
9
16
25


In [ ]:
import json

In [ ]:
example = {
    'Abhiram' : "CSE",
    'Rohan' : 'EE',
    'Deep' : 'MA',
    'Vyoma' : 'MA',
}

In [ ]:
with open('test_3.json','w') as fp:
    json.dump(example, fp)

In [ ]:
with open('test_3.json', 'r') as fp:
    data = json.load(fp)

print(data)

{'Abhiram': 'CSE', 'Rohan': 'EE', 'Deep': 'MA', 'Vyoma': 'MA'}


# **String**
 immutable

In [ ]:
s='vyoma'+'vyoma'
s

'vyomavyoma'

In [ ]:
s=10* 'vyoma'
s

'vyomavyomavyomavyomavyomavyomavyomavyomavyomavyoma'

In [ ]:
s='vyoma\'s laptop'  #\ removes the org meaning of the ' in between
s

"vyoma's laptop"

In [ ]:
s='c:\docs\new'
s

'c:\\docs\new'

In [ ]:
s='c \nseeeee'
s

'c \nseeeee'

In [ ]:
x=3
3+x

6

In [ ]:
_+8  #_ =output of previous operation

14

In [ ]:
s='vyoma'  #0,1,2,3,4
s[3]

'm'

In [ ]:
s[3:]

'ma'

In [ ]:
s[0]='m'   #in python strings are immutable: cannot change value once assigned

TypeError: ignored

In [ ]:
'my ' +' name ' +'is '+ s[3:]

'my  name is ma'

# **List**
* They are mutable(can be changed)
* Different datatypes can be entered in a single list

In [ ]:
nums=[1,2,3,4,5,6]
nums.append(45)   #at last
nums.insert(2,56)  #index, element
nums

[1, 2, 56, 3, 4, 5, 6, 45]

In [ ]:
nums.remove(4)  #specify the element to be removed
nums

[1, 2, 56, 3, 6, 45]

In [ ]:
nums.pop()  #when not specified, last one like stack

45

In [ ]:
nums.pop(1)  #at index

2

In [ ]:
nums.extend([45,56,78])
nums

[1, 56, 3, 6, 45, 56, 78]

In [ ]:
del nums[2:4]  #2,3
nums

[1, 56, 45, 56, 78]

In [ ]:
min(nums)

1

In [ ]:
max(nums)

78

In [ ]:
sum(nums)

236

In [ ]:
nums.sort()
nums

[1, 45, 56, 56, 78]

# **Tuple**
IMMUTABLE and faster than LIST

In [ ]:
tup=(1,2,3,4,4,5)
tup.count(4)

2

In [ ]:
tup.index(3)

2

In [ ]:
tup[2]=9


TypeError: ignored

In [ ]:
tup[1]

2

# **Set**
--> just like hash: very fast -->does not follow any sequence and give out unique elements

No indexing: since no specific sequence

In [ ]:
s={2,2,3,67,54,34,67,33}
s

{2, 3, 33, 34, 54, 67}

In [ ]:
#s[0] can not use

for i in s:
  print(i)

33
2
67
3
34
54


# **Dictionary**

In [ ]:
d={'Vyoma':{'Bday':'Oct','Leisure':'Painting'},'Deep':['Dec','Sleep']}
print(d.get('Vyoma'))
print(d['Deep'])  #accessed only by keys
print(d['Deep'][0])  #List
print(d['Vyoma']['Bday']) #dict

keys=[1,2,3]
values=['Vyoma','Deep','Shikhar']
d2=dict(zip(keys,values))
d2

{'Bday': 'Oct', 'Leisure': 'Painting'}
['Dec', 'Sleep']
Dec
Oct


{1: 'Vyoma', 2: 'Deep', 3: 'Shikhar'}

In [ ]:
x=5
id(x) 3---> address

#python cnt make variables constant


94793761585792

# **Datatypes**

In [ ]:
x=5.0
print(type(x))
y=5+8j
print(type(y))
#none, numeric(int,float,complex,bool),list,tuple,set,dict,range,string

<class 'float'>
<class 'complex'>


# **Operators**

# **Math Functions**

In [ ]:
import math as m
print(m.sqrt(49))
print(m.pow(8,3))
print(m.sin(0.5))

7.0
512.0
0.479425538604203


In [ ]:
from math import pow
pow(8,3)

512.0

In [ ]:
help('math')

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    copysign(x, y, /)
        Return a float with the magnitude (absolute value) of x but the sign of y.
   

# **User Input**

takes input as string type always

In [ ]:
x=input('enter First number: ')
print(type(x))
a=int(x)
y=input('enter 2nd number: ')
b=int(y)
print(a+b)

enter First number: 4
<class 'str'>
enter 2nd number: 4
8


In [ ]:
num=int(input('enter num'))
print(num)

enter num7
7


In [ ]:
ch=input('enter char')
print(ch)

enter charpq
pq


In [ ]:
ch=input('enter char')[0]
print(ch)

enter charpjj
p


In [ ]:
result=eval(input('enter expression'))
print(result)

enter expression2+8-8
2


In [ ]:
lst=[]
for i in range(5):
     lst.append(int(input('enter numbers: ')))
print(lst)

enter numbers: 2
enter numbers: 3
enter numbers: 4
enter numbers: 5
enter numbers: 6
[2, 3, 4, 5, 6]


# **if else**

# **while loop**

# **for loop**

# **Break, continue and pass**

In [ ]:
for i in range(11):
  if i>5:
    break  #come out of the loop
  else:
    print(i)

0
1
2
3
4
5


In [ ]:
for i in range(11):
  if i%3==0:
    continue  #skip that iteration
  else:
    print(i)

1
2
4
5
7
8
10


In [ ]:
#printing even numbers
for i in range(11):
  if i%2!=0:
    pass  #do nthing for this execution
  else:
    print(i)

0
2
4
6
8
10


# **PATTERN PRINT:**

1 1 1 1

1 1 1 1

1 1 1 1

1 1 1 1

In [ ]:
for i in range(4):
  for j in range(4):
    print(1, end='')  #end--> when you dont wana come to new line
  print()

1111
1111
1111
1111


In [ ]:
for i in range(4):
  for j in range(i+1):
    print(1, end='')  #end--> when you dont wana come to new line
  print()

1
11
111
1111


In [ ]:
for i in range(4):
  for j in range(4-i):  #i=0,1,2,3--->j=4,3,2,1
    print(1, end='')  #end--> when you dont wana come to new line
  print()

1111
111
11
1


In [ ]:
#1
#2 3
#4 5 6
#7 8 9 10

count=1
for i in range(4):
  for j in range(i+1):
    print(count,end=' ')  #end--> when you dont wana come to new line
    count+=1
  print()

1 
2 3 
4 5 6 
7 8 9 10 


In [ ]:
#1 2 3 4
#2 3 4
#3 4
#4


for i in range(4):
  for j in range(4-i):

    print(j+i+1,end=' ')  #end--> when you dont wana come to new line

  print()


1 2 3 4 
2 3 4 
3 4 
4 


In [ ]:
#  1
# 111
#11111

n=10
for i in range(n):
  for j in range(2*n-1):
    if i+j >=n-1 and j-i<=n-1:
      print("*",end='')
    else:
      print(" ",end='')
  print('\n')

         *         

        ***        

       *****       

      *******      

     *********     

    ***********    

   *************   

  ***************  

 ***************** 

*******************



In [ ]:
for i in range(3):
  for j in range(5):
    if i+j >=2 and i+j <=2*(i+1):
      print("*",end='')
    else:
      print(" ",end='')
  print('\n')

  *  

 *** 

*****



In [ ]:
for i in range(3):
  for j in range(5):
    if j>=2-i and j<=2+i:
      print("*",end='')
    else:
      print(" ",end='')
  print('\n')

  *  

 *** 

*****



In [ ]:
for i in range(5):
  for j in range(6):
    if j==2*i+1:
      print("*",end='')
    else:
      print(" ",end='')
  print('\n')

 *    

   *  

     *

      

      



is Prime?
using for else

In [ ]:
num=7
for i in range(2,num):
  if num%i==0:
    print('not prime')
else:
    print('prime')

prime


# **Array**

In [ ]:
#import array
from array import *
vals= array('i',[1,3,4,5,-1])
print(vals)
print(vals.typecode)
print(vals.buffer_info())  #address, size
vals.reverse()
print(vals)

array('i', [1, 3, 4, 5, -1])
i
(139729581694416, 5)
array('i', [-1, 5, 4, 3, 1])


In [ ]:
newarr=array(vals.typecode, (a*2 for a in vals))
for a in newarr:
  print(a)

-2
10
8
6
2


In [ ]:
arr= array('i',[])

n=int(input('enter length of array: '))

for i in range(n):
  x=int(input('enter value: '))
  arr.append(x)

print(arr)

enter length of array: 4
enter value: 2
enter value: 3
enter value: 4
enter value: 5
array('i', [2, 3, 4, 5])


In [ ]:
print(arr.index(4))

2


>**NOTE: array package does not support multi dimensional array**

# **NUMPY**

Arrays: Different ways of creating

In [ ]:
import numpy as np
arr= np.array([1,2,3,4 ])
print(arr.dtype)
print(arr)

int64
[1 2 3 4]


In [ ]:
arr=np.array([1,2,3,4.0])
print(arr.dtype)
print(arr)

float64
[1. 2. 3. 4.]


In [ ]:
arr=np.array([1,2,3,4],float)
print(arr.dtype)
print(arr)

float64
[1. 2. 3. 4.]


In [ ]:
arr=np.linspace(0,10,14)  #start,end,steps(no of parts)  /float  /bydefault=50 parts
#gap between two elements is same
arr

array([ 0.        ,  0.76923077,  1.53846154,  2.30769231,  3.07692308,
        3.84615385,  4.61538462,  5.38461538,  6.15384615,  6.92307692,
        7.69230769,  8.46153846,  9.23076923, 10.        ])

In [ ]:
arr=np.arange(1,15,2)  #start,stop, steps(skipping)
arr

array([ 1,  3,  5,  7,  9, 11, 13])

In [ ]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr=np.ones(6,int)
arr

array([1, 1, 1, 1, 1, 1])

**Different operations on Arrays using Numpy**

In [ ]:
arr=arr+5
arr

array([6, 6, 6, 6, 6, 6])

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([2,2,6,4,10])
arr1+arr2

array([ 3,  4,  9,  8, 15])

In [ ]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [ ]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [ ]:
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [ ]:
np.sum(arr1)

15

In [ ]:
np.sort([1,6,3,2,0,89,67,36])

array([ 0,  1,  2,  3,  6, 36, 67, 89])

In [ ]:
np.unique([1,2,2,3,3,35,66,55,66,3,4])

array([ 1,  2,  3,  4, 35, 55, 66])

In [ ]:
np.concatenate([ [1,2,3,4,5] , [3,4,4,55,66] ])

array([ 1,  2,  3,  4,  5,  3,  4,  4, 55, 66])

Copying an array

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=arr1

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))   #same array-->same address

[1 2 3 4 5]
[1 2 3 4 5]
140207518175920
140207518175920


In [ ]:
#same array with different address--> SHALLOW COPY
arr1=np.array([1,2,3,4,5])
arr2=arr1.view()

arr1[2]=45
print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[ 1  2 45  4  5]
[ 1  2 45  4  5]
140207527723136
140207527726096


In [ ]:
#differnt arrays with different addresses--> DEEP COPY
arr1=np.array([1,2,3,4,5])
arr2=arr1.copy()

arr1[2]=45
print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[ 1  2 45  4  5]
[1 2 3 4 5]
140207518078096
140207521066800


**Multi dimensional Array**

In [ ]:
arr=np.array([ [1,2,3,4,5,6], [2,3,455,66,3,8]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[  1   2   3   4   5   6]
 [  2   3 455  66   3   8]]
2
(2, 6)
12


Converting 2D array --> 1D array

In [ ]:
arr2=arr.flatten()
print(arr2)
print(arr2.shape)

[  1   2   3   4   5   6   2   3 455  66   3   8]
(12,)


Converting 1D array--> 2D array

In [ ]:
arr3=arr2.reshape(6,2)
print(arr3)
print(arr3.shape)

[[  1   2]
 [  3   4]
 [  5   6]
 [  2   3]
 [455  66]
 [  3   8]]
(6, 2)


1D --> 3D

In [ ]:
arr4=arr2.reshape(3,2,2)
print(arr4)

[[[  1   2]
  [  3   4]]

 [[  5   6]
  [  2   3]]

 [[455  66]
  [  3   8]]]


**Multi dimensional Array --> Matrix**

In [ ]:
arr=np.array([ [1,2,3,4], [2,3,455,66]])
mat=np.matrix(arr)
print(mat)

[[  1   2   3   4]
 [  2   3 455  66]]


In [ ]:
mat=np.matrix('1,2,3 ; 2,3,4 ; 6,7,8')
print(mat)

[[1 2 3]
 [2 3 4]
 [6 7 8]]


In [ ]:
print(np.diagonal(mat))

[1 3 8]


In [ ]:
print(mat.max())

8


In [ ]:
m1=np.matrix('1,2,3 ; 2,3,4 ; 6,7,8')
m2=np.matrix('1,1,2 ; 2,1,2 ; 3,1,1')

m3=m1+m2
print(m3)

[[2 3 5]
 [4 4 6]
 [9 8 9]]


In [ ]:
m1=np.matrix('1,2,3 ; 2,3,4 ; 6,7,8')
m2=np.matrix('1,1,2 ; 2,1,2 ; 3,1,1')

print(m1)
print(m2)
m3=m1*m2
print(m3)

[[1 2 3]
 [2 3 4]
 [6 7 8]]
[[1 1 2]
 [2 1 2]
 [3 1 1]]
[[14  6  9]
 [20  9 14]
 [44 21 34]]


In [ ]:
m1=np.matrix('1,2,3 ; 2,3,4 ; 6,7,8')
m2=np.matrix('1,1,2 ; 2,1,2 ; 3,1,1')

print(m1)
print(m2)

m3=np.matmul(m1,m2)
print(m3)

[[1 2 3]
 [2 3 4]
 [6 7 8]]
[[1 1 2]
 [2 1 2]
 [3 1 1]]
[[14  6  9]
 [20  9 14]
 [44 21 34]]


# **Functions, Function arguments**

In [ ]:
def update(x):
  print(id(x)) #--->pointing same id of a=10

  x=8  #--->changing the value means updating the address as well
  print(id(x))  #--> new address
  print('x:',x) #-->updated value

a=10
print(id(a))

update(a)
print('a:',a)  #--> not changed here as integers, strings are immutable


93874774580000
93874774580000
93874774579936
x: 8
a: 10


In case of list

In [ ]:
def update(x):
  print(id(x)) #--->pointing same id of a=10

  x[2]=8  #--->changing the value means changing at the same address
  print(id(x))  #--> same address
  print('x:',x) #-->updated value

a=[10,20,30]
print(id(a))

update(a)
print('a:',a)  #--> changed here as well, list is mutable


140207517822320
140207517822320
140207517822320
x: [10, 20, 8]
a: [10, 20, 8]


**Types of function arguments**

In [ ]:
def person(name,age):
  print(name)
  print(age)

person('vyoma','16')  #position arg


vyoma
16


In [ ]:
def person(name,age):
  print(name)
  print(age)

person(age='16',name='vyoma')  #keyword arg(when you dont know the position )


vyoma
16


In [ ]:
def person(name,age=18):
  print(name)
  print(age)

person('vyoma')  #default arg


vyoma
18


In [ ]:
def sum(a,*b):  #variable length argument
  print(a)
  print(b)
  print(type(b))

  #c=a
  #for i in b:
    #c=c+i
  #print(c)

sum(1,[2,3,4,5,6,8,99,78])

1
([2, 3, 4, 5, 6, 8, 99, 78],)
<class 'tuple'>


In [ ]:
def sum(*b):  #variable length argument
  #print(a)
  print(b)
  print(type(b))

  c=0
  for i in b:
    c=c+i
  print(c)

sum(1,2,3,4,5,6,8,99,78)

(1, 2, 3, 4, 5, 6, 8, 99, 78)
<class 'tuple'>
206


In [ ]:
#keyword variable length argumnet--> when you dont know hat type of data is user sending, specify the keyword by the usr himself

def person(name, **data):
  print(name)
  print(data)
  print(type(data))
  for i,j in data.items():
    print(i,j)

person('vyoma',city='gzb',age=18)

vyoma
{'city': 'gzb', 'age': 18}
<class 'dict'>
city gzb
age 18


# **Global - Local**

In [ ]:
a=15
def hello():
  a=10
  print('local: ',a)

hello()

print('global: ',a)

local:  10
global:  15


In [ ]:
a=15
def hello():
  global a
  a=10  #-->as a global variable
  print('updating: ',a)

hello()

print('global: ',a)

updating:  10
global:  10


**having local and global variable with same name in same function**

In [ ]:
a=10
print(id(a))

def hello():

  a=9 #local

  x=globals()['a']  #globals returns all the global variables , so specify which you need
  print('local: ',a)
  print('global in function: ',x)
  print(id(x))  #-->pointing to same address of global a

  globals()['a']=15  #-->updating the global variable outside without effecting the local in function

hello()

print('global outside: ',a)


93940312607520
local:  9
global in function:  10
93940312607520
global outside:  15


# **Returning the odd and even elements from a list after passing through function**

In [ ]:
lst=[]
for i in range(5):
     lst.append(int(input('enter numbers: ')))
print(lst)

even=[]
odd=[]
def count(x):
  for i in x:
    if i%2==0:
      even.append(i)
    else:
      odd.append(i)
  return even,odd


even,odd=count(lst)
print(even)
print(odd)

enter numbers: 45
enter numbers: 34
enter numbers: 22
enter numbers: 23
enter numbers: 12
[45, 34, 22, 23, 12]
[34, 22, 12]
[45, 23]


# **Fibbonacci Seeries:**
0 1 1 2 3 5 8 ........**


In [ ]:

lis=[]
def fib(n):
  x=0
  y=1
  f=0
  if n<0:
    print('enter only positive numbers ')

  elif n==1:
    lis.append(x)

  else:
    lis.append(x)
    lis.append(y)


    for i in range(2,n):
      f=(x+y)
      x=y
      y=f
      lis.append(f)

  return lis

fib(8)

[0, 1, 1, 2, 3, 5, 8, 13]

# **Factorial**

In [ ]:
#6!=1x2x3x4x5x6

def fact(n):
  f=1
  for i in range(1,n+1):
    f=f*i

  return f

fact(5)

120

# **Recursion**

In [ ]:
import sys

sys.setrecursionlimit(1000)
print(sys.getrecursionlimit())

i=0
def greet():
  global i
  i+=1

  print('hello',i)
  greet()

greet()

In [ ]:
#6!=1x2x3x4x5x6

def fact(n):
  if n==0:  #limit deni padegi na
    return 1

  f=n*fact(n-1)

  return f

fact(5)

120

# **Anonymous Function: lambda**

In [ ]:
#need to use once tht function and dont want to define name of the function
#one expression to return
#pass functions to function: functions are object in python
#----> Use Lambda

#define anonymous functions under Lambda and take arg and return operation in one line
#lambda argument: return operation on argument

x=lambda a: a*a  #x represents your function as object
ans=x(5)  #a=5
print(ans)

#you can pass any number of arguments but have one expression of all

x=lambda a,b,c: a+b+c

print(x(4,5,6))


25
15


# **Filter map reduce**

In [ ]:
#Function
def is_even(n):
  return n%2==0

nums=[1,2,3,4,5,6,7,88]
evens=list(filter(is_even,nums))   #takes in (function , input)
print(evens)

[2, 4, 6, 88]


In [ ]:
#anonymous function
e=lambda n: n%2==0

nums=[1,2,3,4,5,6,7,88]
evens=list(filter(e,nums))   #takes in (function , input)
print(evens)

[2, 4, 6, 88]


In [ ]:
nums=[1,2,3,4,5,6,7,88]
evens=list(filter(lambda n: n%2==0  ,nums))   #takes in (function , input)

doubles=list(map(lambda n:n*2, evens))  #takes in (function , iterable) --> used where u want to map values to some other values

from functools import reduce
sum=reduce(lambda a,b: a+b, doubles)  #takes in function ,sequence # at one takes in two values to reduce

print(evens)
print(doubles)
print(sum)

[2, 4, 6, 88]
[4, 8, 12, 176]
200


# **Decorators**

Changing in Function without touching the Function

Add extra features in existing function

In [ ]:
def div(a,b):
  print(a/b)

div(2,4)

0.5


In [ ]:
def div(a,b):
  print(a/b)

#USING: in python, we can have functions inside functions and functions are object

def smart_div(func):

  def inner(a,b):
    if a<b:
      a,b=b,a
    return func(a,b)

  return inner

div1=smart_div(div)

div1(2,4)

2.0


# **OOPS**

**class and object**

In [ ]:
class Computer:
  def config(self):
    print('My name is Vyoma')

com1=Computer()  #object creation

Computer.config(com1)
com1.config()  #using object itself to call the method: object apneap le ra method

My name is Vyoma
My name is Vyoma


__init__ method

In [ ]:
class Computer:

  def __init__(self,cpu,ram):  #just like constructure, call krne ki no need, to initialise the variables,, special method
                               #self for the object itself: com1
    self.cpu= cpu #pasing to the object #i5 goes to the argumnet , assigned to self  , object com1 ko variable ki values mil jayegi
    self.ram= ram



  def config(self):
    print('My name is Vyoma')
    print(self.cpu,self.ram)

com1=Computer('i5',16)

#Computer.config(com1)
com1.config()

My name is Vyoma
i5 16


1. **size of the object in heap:**
depends on the size of each variable and number of variables

2. **who allocates size of object:** Constructor


In [ ]:
class Computer:

  def __init__(self):
    self.name='Vyoma'
    self.age=34

  def update(self):
    self.age=24

  def compare(self,other):
    if self.age==other.age:
      return True
    else:
      return False


com1=Computer()
com2=Computer()
print(id(com1))  #differnt address
print(id(com2))

com1.update()

com1.name='Deep'

print(com1.name)  #changing
print(com2.name)

print(com1.age)  #updated
print(com2.age)

if com1.compare(com2):  #com1 to self,,,, com2 to other
  print('same')
else:
  print('diff')

139856403242128
139856403241168
Deep
Vyoma
24
34
diff


Types of variables: instance and class

In [ ]:
class Computer:

  wheels=4   #class variable

  def __init__(self):

    #instance variable: can be changed outside class: inside init
    self.mil=10
    self.car='BMW'




com1=Computer()
com2=Computer()

com1.mil=5  #change for only com1 object, not com2 object

Computer.wheels=6  #will change for all objects , shared

print(com1.mil, com1.car, com1.wheels)

print(com2.mil, com2.car, com2.wheels)

5 BMW 6
10 BMW 6


Types of method: class, instance and static

In [ ]:
#when working with instance methd: use self  : instance variables
#with class method : use cls : for class variables
#with static method: not concerned with any variable


class students:

  school='dewan'  #static variable    can be used with class method not instance method

  def __init__(self,m1,m2,m3):
    self.m1=m1   #m1,m2,m3 => instance variables with instance method
    self.m2=m2
    self.m3=m3

  def avg(self):   #instance method as we are passing self to get the object s1 or s2 in this

    return (self.m1 + self.m2 + self.m3)/3

  # Types of instance methods:
  #accessor method: when fetching te instance variable say m2  #--> getters
  #mutator method: when want to modify the value of variable say m1  #---> setters

  def get_m1(self):   #accessor-->getters
    return self.m1

  def set_m1(self,value):  #mutator==> setters\\
    self.m1=value

  @classmethod  #to use classmethod need to define as classmethod using DECORATOR
  def getschoolname(cls):
    return cls.school  #class variable: cls.var

  @staticmethod
  def info():
    print('hello vyoma')
    return True

s1=students(33,45,67)
s2=students(31,65,17)

print(s1.avg())
print(s2.avg())

print(students.getschoolname())

print('hi',students.info())


48.333333333333336
37.666666666666664
dewan
hello vyoma
hi True


## **Encapsulation**

In [ ]:
# Python program to
# demonstrate private members

# Creating a Base class
class Base:
    def __init__(self):
        self.a = "GeeksforGeeks"
        self.__c = "GeeksforGeeks"

# Creating a derived class
class Derived(Base):
    def __init__(self):

        # Calling constructor of
        # Base class
        Base.__init__(self)
        print("Calling private member of base class: ")
        print(self.__c)


# Driver code
obj1 = Base()
print(obj1.a)

# Uncommenting print(obj1.c) will
# raise an AttributeError

# Uncommenting obj2 = Derived() will
# also raise an AtrributeError as
# private member of base class
# is called inside derived class

## **Inner Class**

* creating the object of inner class inside the outer class

* creating the object of inner class outside the outer class provided you call it using the outer class name

In [ ]:
class student:
  def __init__(self,name,roll):
    self.name=name
    self.roll=roll
    #self.lap=self.laptop()   #object of laptop(inner class) inside outer class

  def show(self):
    print(self.name,self.roll)

  class laptop:    #----INNER CLASS--
    def __init__(self):
      self.cpu='i5'
      self.brand='dell'

s1=student('Vyoma',20)
s1.show()

#s1.lap.brand   #lap is in student class. so object of student =s1, then object of laptop=lap


#lap1=s1.lap
#lap1.brand


#creating object for inner class outside the outer class
lap1=student.laptop()
lap1.brand


Vyoma 20


'dell'

we can create another method with the same name

In [ ]:
class student:
  def __init__(self,name,roll):
    self.name=name
    self.roll=roll
    self.lap=self.laptop()   #object of laptop(inner class) inside outer class

  def show(self):
    print(self.name,self.roll)
    self.lap.show()

  class laptop:    #----INNER CLASS--
    def __init__(self):
      self.cpu='i5'
      self.brand='dell'

    def show(self):   #we can create another method with the same name
      print(self.brand,self.cpu)

s1=student('Vyoma',20)
s1.show()

#s1.lap.brand   #lap is in student class. so object of student =s1, then object of laptop=lap


#lap1=s1.lap
#lap1.brand


#creating object for inner class outside the outer class
#lap1=student.laptop()
#lap1.brand


Vyoma 20
dell i5


## **Inheritance**

using features of existing class

Single Level

In [ ]:
class A:  #---->  Super Class/ Parent Class
  def feature1(self):
    print('feature1')

  def feature2(self):
    print('feature2')

class B(A):     #--> Sub Class/CHild Class, inherting the methods of A.
  def feature3(self):
    print('feature3')

  def feature4(self):
    print('feature4')

a1=A()
#a1.feature1()

b1=B()
b1.feature1()

feature1


Multi level: B inherits A and C inherits B (means of A and B both)

In [ ]:
class A:  #---->  Super Class/ GrandParent Class
  def feature1(self):
    print('feature1')

  def feature2(self):
    print('feature2')

class B(A):     #--> Sub Class1/Parent Class, inherting the methods of A.
  def feature3(self):
    print('feature3')

  def feature4(self):
    print('feature4')

class C(B):  #--> Sub Class2 of super class (parent here--sub class1) /Child Class, inherting the methods of A and B.
  def feature5(self):
    print('feature5')

a1=A()
#a1.feature1()

b1=B()
#b1.feature1()

c1=C()
c1.feature1()

feature1


Multiple Inheritance--> C inherting both A and B

In [ ]:
class A:  #---->  Parent Class1
  def feature1(self):
    print('feature1')

  def feature2(self):
    print('feature2')

class B():     #--> Parent Class2.
  def feature3(self):
    print('feature3')

  def feature4(self):
    print('feature4')

class C(A,B):  #--> Sub Class of super class(Parent1 and Parent2 )/Child Class, inherting the methods of A and B.
  def feature5(self):
    print('feature5')

a1=A()
#a1.feature1()

b1=B()
b1.feature3()

c1=C()
c1.feature1()

feature3
feature1


Constructor in inheritance

In [ ]:
class A:  #---->  Super Class/ Parent Class

  def __init__(self):
    print('init in A ')

  def feature1(self):
    print('feature1')

  def feature2(self):
    print('feature2')

class B(A):     #--> Sub Class/CHild Class, inherting the methods of A.
  def feature3(self):
    print('feature3')

  def feature4(self):
    print('feature4')

#a1=A()
#a1.feature1()

b1=B()  #object of child class will still call the constructor of parent class
        #SINCE IT IS NOT HAVING IT'S init METHOD, THATS WHY IT IS GOING TO A .
b1.feature1()

init in A 
feature1


In [ ]:
class A:  #---->  Super Class/ Parent Class

  def __init__(self):
    print('init in A ')

  def feature1(self):
    print('feature1')

  def feature2(self):
    print('feature2')

class B(A):     #--> Sub Class/CHild Class, inherting the methods of A.
  def __init__(self):
    print('init in B')

  def feature3(self):
    print('feature3')

  def feature4(self):
    print('feature4')

#a1=A()
#a1.feature1()

b1=B()  #object of child class will call the constructor of its OWN.
b1.feature1()

init in B
feature1


In [ ]:
class A:  #---->  Super Class/ Parent Class

  def __init__(self):
    print('init in A ')

  def feature1(self):
    print('feature1')

  def feature2(self):
    print('feature2')

class B(A):     #--> Sub Class/CHild Class, inherting the methods of A.

  def __init__(self):
    super().__init__()   #to get the features from super class , we use uper keyword
    print('init in B')

  def feature3(self):
    print('feature3')

  def feature4(self):
    print('feature4')

#a1=A()
#a1.feature1()

b1=B()  #object of child class will call the constructor of the Super Class and its own.
b1.feature1()

init in A 
init in B
feature1


Multiple Inheritance:::::::Calling the init of two super classes from the child

In [ ]:
class A:  #---->  Super Class/ Parent Class

  def __init__(self):
    print('init in A ')

  def feature1(self):
    print('feature1-A')

  def feature2(self):
    print('feature2')

class B():     #--> Sub Class/CHild Class, inherting the methods of A.

  def __init__(self):
    print('init in B')

  def feature1(self):
    print('feature1-B')

  def feature4(self):
    print('feature4')

class C(A,B):     #IN MULTIPLE INHERITANCE,,,, it PREFERS FROM Left to Right---> METHOD RESOLUTION ORDER
  def __init__(self):
    super().__init__()  #will get the init of A ::: biased
    super().feature2()   #can other methodds from super class as well
    print('init in C ')


c1=C()
c1.feature1()   #it will go to its left first , that is A.

init in A 
feature2
init in C 
feature1-A


## **Ploymorphism**:::

meaning Many forms



*   Duck typing
*   Operator Overloading
*   Method Overloading
*   Method Overriding



Duck typing

In [ ]:
#In python we can differnt data types with the same varaible name:
#DYNAMIC TYPING
x=5
x='VYoma'

#these will be stored in two differnt memories

#same for classes:

class Pycharm:
  def execute(self):
    print('Pycharm')

class MyEditor:
  def execute(self):    #YoU HAVE TO KEEP THE METHOD NAME SAME , No matter what
     print('My editor')

class Vyoma:
  def code(self, ide):   #passing the object of another class as argument
    ide.execute()        #callimg the method of another class


#i=Pycharm()   #object of Pycharm class
i=MyEditor()   #changing the type of ide(object to call) provided the method names are same

vyo= Vyoma()
vyo.code(i)    #passing the object of another to another

My editor


Operator Overloading

In [ ]:
a=5
b=6

print(a+b)

print(int.__add__(a,b))
#int class--> method add behind the scenes


class student:
  def __init__(self,m1,m2):
    self.m1=m1
    self.m2=m2

  def __add__(self,other):
    m1=self.m1 + other.m1
    m2=self.m2 + other.m2
    p3= student(m1,m2)
    return p3


s1=student(7,8)
s2=student(1,2)

s3=s1+s2
print(s3.m1)

11
11
8


Methods overriding and overloading


In python : NO method overloading is there : creating method with same name but with different number of arguments in same class

Method overriding: creating method with same name and same number of argumnts but in diffrent class(inheritance mei use hota)



In [ ]:
                      # (---Method Overloading with tricks---)

class Student:

    def __init__(self,m1,m2):
        self.m1 = m1
        self.m2 = m2

    def sum(self,a=None,b=None,c=None):

      s = 0

      if a!=None and b!=None and c!=None:
           s = a+b+c
      elif a!=None and b!=None:
            s = a+b
      else:
            s = a

      return s

s1 = Student(58,69)
print(s1.sum(5))

5


In [ ]:
                        #(---Method Overriding---)

class A:

    def show(self):
        print("in A Show")

class B(A):

    def show(self):   #method with same name and same number of arguments
                      #calls method of subclass
                      #overrides the show method of A, which it can call because of inheritance
        super().show() # calling super class method
        print("in B Show")


a1 = B()
a1.show()

in A Show
in B Show


# **Abstract class and method**

abstract method: no body

abstract class:having abstract method with no body,, must have atleast one abstract method


but in python we dont have abstract class concept by default,,, we create by using some tricks that is import ABC

In [ ]:
#not abstract class yet

class vyoma:
  def code(self):
    pass

s=vyoma()
s.code()

if you abstract class and you cant get object of it because we have a method which is not defined

In [ ]:
from abc import ABC, abstractmethod   #ABC=Abstract Base Class
class vyoma(ABC):   #just decalared
  @abstractmethod
  def code(self):
    pass

s=vyoma()
s.code()


TypeError: ignored

In [ ]:
from abc import ABC, abstractmethod   #ABC=Abstract Base Class
class vyoma(ABC):   #just decalared
  @abstractmethod
  def code(self):
    pass

class another(vyoma):
  def code(self):
    print(7)

#s=vyoma()
p=another() #compulsory to define the method named as code , otherwise it is still abstract and object cnt be created
p.code()


7


# **Iterator**

In [ ]:
nums=[1,2,3,4,5]

it=iter(nums)

print(it.__next__())
print(it.__next__())  #preserves the previous state and gives out the next value without using index
print(it.__next__())
print(next(it))

1
2
3
4


In [ ]:
class TopTen:
  def __init__(self):
    self.num = 1

  def __iter__(self):
    return self

  def __next__(self):

    if self.num <= 10:
      val = self.num
      self.num += 1

      return val
    else:
      raise StopIteration #to stop a for loop


values = TopTen()

print(next(values))

# print(values.__next__())
# print(values.__next__())

for i in values:  #will start after the 1st state of next, for mei bhi in built  ext method hota -->2to10
     print(i)

1


oonly way to stop a for loop is raise an exception StopIteration

# **generators**

creates an iterator yield craetes its object,, so use next to get the values

In [ ]:
def topten():

     yield 1
     yield 2
     yield 3
     yield 4

values =  topten()

print(values.__next__())
print(values.__next__())

1
2


In [ ]:
def topten():

    n = 1

    while n <= 10:
        sq = n*n
        yield sq
        n += 1


values =  topten()

for i in values:
    print(i)

# **Exception handling**

In [ ]:
#runtime error

a=8
b=0


try:

  k=int(input('Enter number'))
  print(k)   #jase hi ek error ayi, it will jump out of loop and prints the exception

  print(a/b)


except ZeroDivisionError as e:
  print('cant divide by zero:',e)

except ValueError as e:
  print('input input:',e)

except Exception as e:   #whenever error
  print('WRONG',e)


finally:    #will be executed even if we get the error or not
  print('closed')


Enter numberp
input input: invalid literal for int() with base 10: 'p'
closed


# **File Handling**

In [ ]:
f1=open('file','a')  #append one after other
f1.write('Hy my name is Vyoma\n I love painting')

36

In [ ]:
f1=open('file1','w')  #append one after other
f1.write('Vyoma')

5

In [ ]:
f1=open('file','r')
print(f1.read())

Hy my name is Vyoma
 I love paintingHy my name is Vyoma
 I love painting


In [ ]:
f1=open('file','r')
print(f1.readline())  #prints line one by one
print(f1.readline())

Hy my name is Vyoma

 I love paintingHy my name is Vyoma



In [ ]:
f=open('file','r')
f1=open('file1','w')

for data in f:
  f1.write(data)

# **Linear Search**

In [ ]:
num=[1,2,3,4,5]
n=5
pos=-1
def search(num,n):
  i=0
  while i<len(num):
    if num[i]==n:
      global pos
      pos=i
      #globals()['pos']=i
      return True
    i+=1
  return False

if search(num,n):
  print('found at ',pos)


found at  4


# **Binary search**

In linear search order of values can be anything

but in Binary search the values have to be in sorted way

In [ ]:
num=[1,2,3,4,5,6,7,8]
n=7
pos=-1
def search(num,n):
  l=0
  u=len(num)-1

  while l<=u:
    mid=(l+u)//2

    if num[mid]==n:
      global pos
      pos=mid
      return True

    else:
      if num[mid]<n:
        l=mid+1   #+1 because mid has been already checekd : so skip
      else:
        u=mid-1

  return False


if search(num,n):
  print('found at ',pos)
else:
  print('not found')

found at  6


# **Bubble sort**

iteration 1: for the swapping and get the biggest number at the end

iteration 2: for outer loop to do the same thing iteratively.... (len of list -1)

In [ ]:
num=[5,3,6,8,7,2,9]

def bubble(num):
  for i in range(len(num)-1,0,-1):
    for j in range(i):
      if num[j]>num[j+1]:
        num[j], num[j+1]= num[j+1], num[j] #Swap

bubble(num)
print(num)

[2, 3, 5, 6, 7, 8, 9]


# **Selection Sort**

ONLY 1 ITERATION:

Find the min value and swap with beginning

and you will have sorted and unsorted array and then get its min ..iterate..

In [ ]:
num=[5,3,6,8,7,2,9]

def selection(num):
  for i in range(len(num)-1):
    minpos=i
    for j in range(i,len(num)):
      if num[j]<num[minpos]:
        minpos=j

    num[i], num[minpos]= num[minpos],num[i]
    print(num)

selection(num)
print(num)

[2, 3, 6, 8, 7, 5, 9]
[2, 3, 6, 8, 7, 5, 9]
[2, 3, 5, 8, 7, 6, 9]
[2, 3, 5, 6, 7, 8, 9]
[2, 3, 5, 6, 7, 8, 9]
[2, 3, 5, 6, 7, 8, 9]
[2, 3, 5, 6, 7, 8, 9]
